### ISSUE TITLE
Support for multi-language model (xx_ent_wiki_sm)

### ISSUE THREAD

**Issue by bittlingmayer** [ines/spacy-js#2]
When actually running, there is this issue:
```
ERROR:waitress:Exception when serving /parse
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/site-packages/waitress/channel.py", line 336, in service
    task.service()
  File "/usr/local/lib/python3.7/site-packages/waitress/task.py", line 175, in service
    self.execute()
  File "/usr/local/lib/python3.7/site-packages/waitress/task.py", line 452, in execute
    app_iter = self.channel.server.application(env, start_response)
  File "/usr/local/lib/python3.7/site-packages/hug/api.py", line 423, in api_auto_instantiate
    return module.__hug_wsgi__(*args, **kwargs)
  File "/usr/local/lib/python3.7/site-packages/falcon/api.py", line 244, in __call__
    responder(req, resp, **params)
  File "/usr/local/lib/python3.7/site-packages/hug/interface.py", line 793, in __call__
    raise exception
  File "/usr/local/lib/python3.7/site-packages/hug/interface.py", line 766, in __call__
    self.render_content(self.call_function(input_parameters), context, request, response, **kwargs)
  File "/usr/local/lib/python3.7/site-packages/hug/interface.py", line 703, in call_function
    return self.interface(**parameters)
  File "/usr/local/lib/python3.7/site-packages/hug/interface.py", line 100, in __call__
    return __hug_internal_self._function(*args, **kwargs)
  File "api/server.py", line 111, in parse
    json.append(doc2json(doc, model))
  File "api/server.py", line 51, in doc2json
    } for sent in doc.sents]
  File "api/server.py", line 48, in <listcomp>
    sents = [{
  File "doc.pyx", line 535, in __get__
ValueError: [E030] Sentence boundaries unset. You can add the 'sentencizer' component to the pipeline with: nlp.add_pipe(nlp.create_pipe('sentencizer')) Alternatively, add the dependency parser, or set sentence boundaries by setting doc[i].is_sent_start.
```
If I had to guess, it seems related to the fact that the xx model does not do syntax parsing.

Is xx supposed to work?  Or am I doing something wrong?
The other models load fine.

spacy info

    Info about spaCy

    spaCy version      2.0.18         
    Location           /usr/local/lib/python3.7/site-packages/spacy
    Platform           Darwin-18.2.0-x86_64-i386-64bit
    Python version     3.7.2          
    Models             pt, es, en, xx 

node -v
v10.15.2

**Comment by bittlingmayer** [comment]
Think it was related to the server being started but not ready.

**Comment by ines** [comment]
Sorry, only saw this now. I think the problem here is that `doc2json` would always try and get the `doc.sents`, even if no sentence boundaries were applied (which is done by the parser by default, but can also be added manually). The `xx` model doesn't have a parser or sentence boundary detection component, so that fails. I just added a fix that should solve this and also updated the repo to use the latest spaCy.
