### ISSUE TITLE
TypeError: process_response() takes 4 positional arguments but 5 were given

### ISSUE THREAD

**Issue by shamoons** [ines/spacy-js#5]
```
ERROR:waitress:Exception while serving /parse
Traceback (most recent call last):
  File "/home/shamoon/.local/share/virtualenvs/olive-ml-W0P_C03Z/lib/python3.6/site-packages/waitress/channel.py", line 356, in service
    task.service()
  File "/home/shamoon/.local/share/virtualenvs/olive-ml-W0P_C03Z/lib/python3.6/site-packages/waitress/task.py", line 176, in service
    self.execute()
  File "/home/shamoon/.local/share/virtualenvs/olive-ml-W0P_C03Z/lib/python3.6/site-packages/waitress/task.py", line 447, in execute
    app_iter = self.channel.server.application(env, start_response)
  File "/home/shamoon/.local/share/virtualenvs/olive-ml-W0P_C03Z/lib/python3.6/site-packages/hug/api.py", line 497, in api_auto_instantiate
    return module.__hug_wsgi__(*args, **kwargs)
  File "falcon/api.py", line 289, in falcon.api.API.__call__
  File "falcon/api.py", line 286, in falcon.api.API.__call__
TypeError: process_response() takes 4 positional arguments but 5 were given
```

**Comment by hrbarz** [comment]
make sure you have version `hug == 2.4.1` installed

**Comment by bronsonavila** [comment]
Adding to the comment from @hrbarz:

I was attempting to use [displaCy](https://github.com/explosion/spacy-services/tree/master/displacy) and encountered the same error when using `hug 2.6.1`, despite the fact that the [requirements](https://github.com/explosion/spacy-services/blob/master/displacy/requirements.txt) for displaCy indicate that it should use `hug>=2.4.0,<3.0.0`. 

The error was resolved when I changed it to instead be `hug>=2.4.0,<2.5.0`. This ultimately resulted in `hug 2.4.8` being installed, which worked fined.
